### ISSUE TITLE
Page doesn't scroll

### ISSUE THREAD

**Issue by xkrt** [KamilKoso/gurufocus-ad-free#1]
Hi!

It looks like the script successfully removes dialog and the bottom block, but I can't scroll the page after that.

**Comment by KamilKoso** [comment]
Hi!

I've spotted where the issue was and solved it. Version 1.1 is already publish so please install it and let me know if that solves the issue

**Comment by xkrt** [comment]
Hi @KamilKoso! Thank you for your work!

I've checked 1.1 and the scroll is working now. But now GF is broken in the other way. Most of GF's widgets now don't show any data/charts. And I see some errors in the dev console.

Could you check it on your Chrome? It might be an important note, that I'm checking not logged in to any account.

**Comment by KamilKoso** [comment]
It appears that i was gutting a bit too much off the site. Now it should work, version 1.2 is released

**Comment by xkrt** [comment]
I've noticed that if I click different tickers several times in this bar paywall shows me
<img width="717" alt="Screenshot 2023-01-19 at 09 09 55" src="https://user-images.githubusercontent.com/428187/213378940-9e06369d-1c6e-46d1-a000-dad60600ae34.png">

I added an option `subtree: true` to:
```
(function () {
  observer.observe(document.body, { subtree: true, childList: true });
})();
```
And now `clearPage` ultimately gets rid of the paywall, but the scroll isn't working again (because the paywall disables it). I added a new block to fix the scroll:
```
function clearPage() {
  let elems = document.querySelectorAll(adsToClear);
  setCookie(pwcouCookie.name, pwcouCookie.desiredValue, pwcouCookie.domain, pwcouCookie.expirationDays);
  elems.forEach((elem) => {
    elem.remove();
  });

  // fix scroll
  let appContainer = document.querySelector('.app-wrapper .el-container')
  if (appContainer.getAttribute('style') == 'height: auto;') {
    appContainer.setAttribute('style', 'height: calc(100vh - 142px);');
  }
}
```

I have been checking my changes for some time and it looks like everything is working now. No dialogs, no paywalls, the scroll is working.
Please note that I know a little about frontend, so my suggestions might be wrong or inefficient :-).
